cache:
  directories:
  - node_modules # cache node_module
language: node_js # set language to node_js
node_js:
  12.16.3 # use node version 12
branches:
  only: 
  - master # auto build and deploy in only master branch
script: # run after installed
- npm install # install node module
- npm run build # build project
install:
  npm install -g firebase-tools # install firebase-cli
after_success:
- firebase use --token ${1//0gm7YWUXPvfjkCgYIARAAGBASNwF-L9IrANQZdh1lLhVEsfJQbMG98K9e9MS6Vynv-M8PyWIGMVckctEq4OROupBx2tIfy1x67Yw} # set firebase token
- firebase use --add ${csmetricconverter
} # set current project
- firebase deploy --non-interactive --token "${1//0gm7YWUXPvfjkCgYIARAAGBASNwF-L9IrANQZdh1lLhVEsfJQbMG98K9e9MS6Vynv-M8PyWIGMVckctEq4OROupBx2tIfy1x67Yw}" # deploy project
